version: '2'

services:
  fhq_db:
    image: mysql:5.7
    volumes:
      - "fhq_mysql_db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HBgvNyuACY # look in fhq-config/fhq.server.conf
      MYSQL_DATABASE: fhqserver # look in fhq-config/fhq.server.conf
      MYSQL_USER: fhqserver # look in fhq-config/fhq.server.conf
      MYSQL_PASSWORD: VveGJemxFb # look in fhq-config/fhq.server.conf
    networks:
      - fhq_net

  fhq_server:
    depends_on:
      - fhq_db
    image: freehackquest/fhq-server:latest
    volumes:
      - "./fhq_data:/usr/share/fhq-server/public"
      - "./fhq_conf:/etc/fhq-server"
      - "./fhq_logs:/var/log/fhq-server"
      
    ports:
      - "1234:1234"
      - "4613:4613"
      - "7080:7080"
    restart: always
    links:
      - "fhq_db"
    networks:
      - fhq_net

volumes:
  fhq_mysql_db:

networks:
  fhq_net:
    driver: bridge