version: '2'

services:
  fhqdev_db:
    image: mysql:5.7
    volumes:
      - "./mysql_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KzhyntJxwt
      MYSQL_DATABASE: fhqserver
      MYSQL_USER: fhqserver
      MYSQL_PASSWORD: fhqserver
    networks:
      - fhqdev_net

  fhqdev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - fhqdev_db
    image: freehackquest/fhq-server-dev:latest
    volumes:
      - "../:/root/fhq-server.git" 
      - "./data/public:/usr/share/fhq-server/public"
      - "./conf.d:/etc/fhq-server"
      - "./logs:/var/log/fhq-server"
    ports:
      - "1234:1234"
      - "4613:4613"
      - "7080:7080"
    restart: always
    networks:
      - fhqdev_net

networks:
  fhqdev_net:
    driver: bridge
